version: "3.3"  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: jodogne/orthanc-plugins
    container_name: orthweb
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
      - site.pem
secrets:
  orthanc.json:
    file: orthanc.json
  site.pem:
    file: sample.localhost.pem
