name: OrthancS3Plugin

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_library:
    runs-on: ubuntu-latest

    steps:
    - name: install apt packages
      run: |
        sudo apt-get update
      
    - name: install vcpkg
      working-directory: '/home/runner'
      run: |
        git init orthweb && cd orthweb
        git remote add origin https://github.com/digihunch/orthweb.git && git config core.sparsecheckout true
        echo 'plugin-builder/*' >> .git/info/sparse-checkout && git pull --depth=1 origin main
        docker --version
      
  publish_image:
    runs-on: ubuntu-latest
    needs: [build_library]
    
    steps:
    - name: start
      run: echo "starting publish_image"
    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: libOrthancAwsS3Storage.so
        path: /home/runner/artifact
    - name: verify artifact
      working-directory: '/home/runner/'
      run: md5sum artifact/libOrthancAwsS3Storage.so
