name: OrthancS3Plugin

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # Instruction to use environment variable https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
  BUILD_TYPE: Release
  MAJOR_NUMBER: 0

jobs:
  build_library:
    runs-on: ubuntu-latest

    steps:
    - name: prepare os packages
      run: |
        sudo apt-get update
    - name: download dockerfile
      working-directory: '/home/runner'
      run: |
        git init orthweb && cd orthweb
        git remote add origin https://github.com/digihunch/orthweb.git && git config core.sparsecheckout true
        echo 'plugin-builder/*' >> .git/info/sparse-checkout && git pull --depth=1 origin main
        docker --version
        
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: |
        echo "VERSION_NUMBER=$MAJOR_NUMBER.$BUILD_NUMBER" >> $GITHUB_ENV
        echo -n "Build number is $BUILD_NUMBER." && echo "Version is $VERSION_NUMBER"
        
    - name: publish docker image locally
      working-directory: '/home/runner/orthweb/plugin-builder'
      run: |
        docker build -t "digihunch/s3-plugin-builder:${{ env.VERSION_NUMBER }}" .
        mkdir out && docker image ls
    outputs:
      version: ${{ env.VERSION_NUMBER }}        
    
  publish_image:
    runs-on: ubuntu-latest
    needs: [build_library]
    
    steps:
    - name: prepare os packages
      run: |
        echo "VERSION_NUMBER=${{ needs.build_library.outputs.version }}" >> $GITHUB_ENV
        echo "VERSION NUMBER is ${{ env.VERSION_NUMBER }}"
        sudo apt-get update
    - name: download dockerfile
      working-directory: '/home/runner'
      run: |
        echo "VERSION NUMBER is ${{ env.VERSION_NUMBER }}"
        git init orthweb && cd orthweb
        git remote add origin https://github.com/digihunch/orthweb.git && git config core.sparsecheckout true
        echo 'orthanc-builder/*' >> .git/info/sparse-checkout && git pull --depth=1 origin main
        docker --version

    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: libOrthancAwsS3Storage.so
        path: /home/runner/orthweb/orthanc-builder
        
    - name: verify artifact
      working-directory: '/home/runner/orthweb/orthanc-builder'
      run: md5sum libOrthancAwsS3Storage.so
      
    #- name: publish docker image locally
    #  working-directory: '/home/runner/orthweb/orthanc-builder'
    #  run: |
    #    docker build -t "digihunch/orthanc-plugin:0.1" .
    #    docker image ls
        
    - name: Login to DockerHub # no need to specify registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true
        
    - name: build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: '/home/runner/orthweb/orthanc-builder'
        #platforms: linux/amd64
        push: true
        tags: |
          digihunch/orthanc-plugin:latest
          digihunch/orthanc-plugin:${{ env.VERSION_NUMBER }}
    
    - name: image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
