name: OrthancS3Plugin

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_library:
    runs-on: ubuntu-latest

    steps:
    - name: prepare os packages
      run: |
        sudo apt-get update
        
    - name: Git Version
      uses: codacy/git-version@2.4.0
   
    - name: download dockerfile
      working-directory: '/home/runner'
      run: |
        git init orthweb && cd orthweb
        git remote add origin https://github.com/digihunch/orthweb.git && git config core.sparsecheckout true
        echo 'plugin-builder/*' >> .git/info/sparse-checkout && git pull --depth=1 origin main
        docker --version
        
    - name: Output Version
      working-directory: '/home/runner/orthweb/plugin-builder'
      run: |
        git-version
        
    - name: publish docker image locally
      working-directory: '/home/runner/orthweb/plugin-builder'
      run: |
        docker build -t "digihunch/s3-plugin-builder:0.1" .
        mkdir out && docker image ls
      
    - name: build plugin with docker
      working-directory: '/home/runner/orthweb/plugin-builder'
      run: |
        # built-in build command
        # docker run --mount src=/home/runner/orthweb/plugin-builder/out,target=/out,type=bind digihunch/s3-plugin-builder:0.1
        # custom build command
        docker run --mount src=/home/runner/orthweb/plugin-builder/out,target=/out,type=bind digihunch/s3-plugin-builder:0.1 /bin/bash -c " \
        cmake -DUSE_VCPKG_PACKAGES=FALSE -DSTATIC_AWS_CLIENT=TRUE -DSTATIC_BUILD=ON /sources/orthanc-object-storage/Aws && \
        cmake --build . --config Release && \
        ./UnitTests && \
        cp /build/*.so /out/"
        md5sum out/libOrthancAwsS3Storage.so
        
    - name: publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: libOrthancAwsS3Storage.so
        path: /home/runner/orthweb/plugin-builder/out/*.so
        retention-days: 1
        
    
  publish_image:
    runs-on: ubuntu-latest
    needs: [build_library]
    
    steps:
    - name: prepare os packages
      run: |
        sudo apt-get update
    - name: download dockerfile
      working-directory: '/home/runner'
      run: |
        git init orthweb && cd orthweb
        git remote add origin https://github.com/digihunch/orthweb.git && git config core.sparsecheckout true
        echo 'orthanc-builder/*' >> .git/info/sparse-checkout && git pull --depth=1 origin main
        docker --version

    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: libOrthancAwsS3Storage.so
        path: /home/runner/orthweb/orthanc-builder
        
    - name: verify artifact
      working-directory: '/home/runner/orthweb/orthanc-builder'
      run: md5sum libOrthancAwsS3Storage.so
      
    #- name: publish docker image locally
    #  working-directory: '/home/runner/orthweb/orthanc-builder'
    #  run: |
    #    docker build -t "digihunch/orthanc-plugin:0.1" .
    #    docker image ls
        
    - name: Login to DockerHub # no need to specify registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true
        
    - name: build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: '/home/runner/orthweb/orthanc-builder'
        #platforms: linux/amd64
        push: true
        tags: |
          digihunch/orthanc-plugin:latest
          digihunch/orthanc-plugin:0.1
    
    - name: image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
