name: OrthancS3Plugin

on:
  workflow_dispatch:

env:
  # Instruction to use environment variable https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
  BUILD_TYPE: Release 
  MAJOR_NUMBER: 0

jobs:
  build_library:
    runs-on: ubuntu-latest

    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}  
        
    - name: prepare os packages
      run: |
        echo "VERSION_NUMBER=$MAJOR_NUMBER.$BUILD_NUMBER" >> $GITHUB_ENV
        echo -n "Build number is $BUILD_NUMBER." && echo "Version is $VERSION_NUMBER"
        sudo apt-get update
        
    - name: download dockerfile
      working-directory: '/home/runner'
      run: |
        git init orthweb && cd orthweb
        git remote add origin https://github.com/digihunch/orthweb.git && git config core.sparsecheckout true
        echo 'plugin-builder/*' >> .git/info/sparse-checkout && git pull --depth=1 origin main
        docker --version
        
    - name: publish docker image for plugin builder locally
      working-directory: '/home/runner/orthweb/plugin-builder'
      run: |
        docker build -t "digihunch/s3-plugin-builder:${{ env.VERSION_NUMBER }}" .
        mkdir out && docker image ls
        
    - name: run docker container to build plugin
      working-directory: '/home/runner/orthweb/plugin-builder'
      run: |
        # built-in build command
        # docker run --mount src=/home/runner/orthweb/plugin-builder/out,target=/out,type=bind "digihunch/s3-plugin-builder:${{ env.VERSION_NUMBER }}"
        # custom build command
        docker run --mount src=/home/runner/orthweb/plugin-builder/out,target=/out,type=bind "digihunch/s3-plugin-builder:${{ env.VERSION_NUMBER }}" /bin/bash -c " \
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
              -DUSE_VCPKG_PACKAGES=FALSE \
              -DSTATIC_AWS_CLIENT=TRUE \
              -DSTANDALONE_BUILD=ON \
              -DALLOW_DOWNLOADS=ON \
              /sources/orthanc-object-storage/Aws && \
        cmake --build . --config Release && \
        ./UnitTests && \
        cp /build/*.so /out/"
        ldd /out/libOrthancAwsS3Storage.so
        echo -n Hash md5sum out/libOrthancAwsS3Storage.so
        
    - name: publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: libOrthancAwsS3Storage.so
        path: /home/runner/orthweb/plugin-builder/out/*.so
        retention-days: 7
        
    outputs:
      version: ${{ env.VERSION_NUMBER }}        
    
  publish_image:
    runs-on: ubuntu-latest
    needs: [build_library]
    
    steps:
    - name: prepare os packages
      run: |
        echo "VERSION_NUMBER=${{ needs.build_library.outputs.version }}" >> $GITHUB_ENV
        sudo apt-get update
        
    - name: download dockerfile
      working-directory: '/home/runner'
      run: |
        git init orthweb && cd orthweb
        git remote add origin https://github.com/digihunch/orthweb.git && git config core.sparsecheckout true
        echo 'orthanc-builder/*' >> .git/info/sparse-checkout && git pull --depth=1 origin main
        docker --version

    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: libOrthancAwsS3Storage.so
        path: /home/runner/orthweb/orthanc-builder
        
    - name: verify artifact
      working-directory: '/home/runner/orthweb/orthanc-builder'
      run: md5sum libOrthancAwsS3Storage.so
        
    - name: Login to DockerHub # no need to specify registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true
        
    - name: build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: '/home/runner/orthweb/orthanc-builder'
        #platforms: linux/amd64
        push: true
        tags: |
          digihunch/orthanc-plugin:latest
          digihunch/orthanc-plugin:${{ env.VERSION_NUMBER }}
    
    - name: image digest
      run: echo Image ${{ steps.docker_build.outputs.digest }} was published to DockerHub as digihunch/orthanc-plugin:${{ env.VERSION_NUMBER }}
